# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{super_simple_admin}
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["metasoarous"]
  s.date = %q{2011-01-08}
  s.description = %q{Provides super simple authentication al a Ryan Bates old screen cast. Creates admin access feature which allows for a single password login for admin tool access.}
  s.email = %q{metasoarous@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.textile"
  ]
  s.files = [
    ".gitignore",
     "Changelog",
     "LICENSE",
     "README.textile",
     "VERSION",
     "lib/super_simple_admin.rb",
     "super_simple_admin.gemspec"
  ]
  s.homepage = %q{http://www.thoughtnode.com}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Provides super simple authentication al a Ryan Bates old screen cast.}
  s.test_files = [
    "spec/rails3/app_root/app/controllers/application_controller.rb",
     "spec/rails3/app_root/app/controllers/sessions_controller.rb",
     "spec/rails3/app_root/app/helpers/application_helper.rb",
     "spec/rails3/app_root/config/application.rb",
     "spec/rails3/app_root/config/boot.rb",
     "spec/rails3/app_root/config/environment.rb",
     "spec/rails3/app_root/config/environments/development.rb",
     "spec/rails3/app_root/config/environments/in_memory.rb",
     "spec/rails3/app_root/config/environments/production.rb",
     "spec/rails3/app_root/config/environments/test.rb",
     "spec/rails3/app_root/config/initializers/backtrace_silencers.rb",
     "spec/rails3/app_root/config/initializers/inflections.rb",
     "spec/rails3/app_root/config/initializers/mime_types.rb",
     "spec/rails3/app_root/config/initializers/secret_token.rb",
     "spec/rails3/app_root/config/initializers/session_store.rb",
     "spec/rails3/app_root/config/routes.rb",
     "spec/rails3/app_root/db/seeds.rb",
     "spec/rails3/spec_helper.rb",
     "spec/rails3/super_simple_admin_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<RedCloth>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<haml>, [">= 0"])
    else
      s.add_dependency(%q<RedCloth>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<haml>, [">= 0"])
    end
  else
    s.add_dependency(%q<RedCloth>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<haml>, [">= 0"])
  end
end

